### ISSUE TITLE
Error when using exllama

### ISSUE THREAD

**Issue by CyberTimon** [FartyPants/Playground#1]
Hello!

I would really love the notebook when it would work.
Everytime I try to generate text in the notebook, I get this error message:
```Output generated in 0.00 seconds (0.00 tokens/s, 0 tokens, context 2, seed 1473755009)
Traceback (most recent call last):
  File "/home/cybertimon/miniconda3/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/cybertimon/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/cybertimon/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/cybertimon/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/home/cybertimon/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/cybertimon/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cybertimon/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/cybertimon/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/cybertimon/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/home/cybertimon/Repositories/text-generation-webui/extensions/Playground/script.py", line 183, in generate_reply_wrapperMY
    if shared.model_type not in ['HF_seq2seq']:
AttributeError: module 'modules.shared' has no attribute 'model_type'```

I say --model_type llama in my start args. I think the problem is that I use exllama as the model loader, which got added a few days ago (This increases the speed).

**Comment by Culpeo** [comment]
It's the same issue with llama.cpp, not only exllama.

**Comment by FartyPants** [comment]
Actually I apparently fixed it today... get the newest version

**Comment by Culpeo** [comment]
Yes, it seems to work now. Good job - thank you! :-)
