### ISSUE TITLE
Failed to load - cannot import name add_lora_exllama

### ISSUE THREAD

**Issue by conor-is-my-name** [FartyPants/Playground#8]
I'm having an issue loading the extension

21:15:37-368368 ERROR    Failed to load the extension "Playground".
Traceback (most recent call last):
  File "C:\Users\USER1\pinokio\api\oobabooga.pinokio.git\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Users\USER1\pinokio\api\oobabooga.pinokio.git\text-generation-webui\extensions\Playground\script.py", line 12, in <module>
    from modules.LoRA import add_lora_autogptq, add_lora_exllama, add_lora_exllamav2
ImportError: cannot import name 'add_lora_exllama' from 'modules.LoRA' (C:\Users\USER1\pinokio\api\oobabooga.pinokio.git\text-generation-webui\modules\LoRA.py)

**Comment by conor-is-my-name** [comment]
I created a pull request with the fix,
v1 of exllama was removed from oobabooga 5 days ago
